version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DSN=poll_db:password@tcp(mysql:3306)/poll_db?charset=utf8mb4&parseTime=True
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - poll-net
    entrypoint: ["sh", "-c", "sleep 10 && /app/poll-app"]

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: poll_db
      MYSQL_USER: poll_db
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 3s
      timeout: 5s
      retries: 30
    networks:
      - poll-net
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=1000

volumes:
  mysql_data:

networks:
  poll-net:
    driver: bridge